name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          # Use Node.js package type which will update package.json
          release-type: node
          # Optional: customize the package name
          package-name: tilfeldigeord.no
